"""PDF Case Pack Renderer.

Generates a structured PDF from an approved case pack.
Per sprint plan S8 and CLAUDE.md:
  - MUST include disclaimer: risk signals and hypotheses only
  - Every citation hyperlinked to stored artifact
  - No accusatory language passes (enforced by auditor gate)
  - PII redacted per content filter

Uses ReportLab for PDF generation (lightweight, no system dependencies).
WeasyPrint is an alternative but requires system-level deps (cairo, pango).
"""

from __future__ import annotations

import io
import logging
from datetime import UTC, datetime
from typing import Any

logger = logging.getLogger(__name__)

# Disclaimer per CLAUDE.md rule #2 — no fraud accusations
_DISCLAIMER = (
    "DISCLAIMER: This document contains risk signals and hypotheses derived from "
    "publicly available federal data. It does not constitute an accusation of "
    "wrongdoing, a legal finding, or evidence of fraud. All claims are classified "
    "as either 'risk signal', 'hypothesis', or 'finding' (supported by cited "
    "artifacts). Independent verification is required before any action."
)

_METHODOLOGY_NOTE = (
    "Methodology: This case pack was assembled by CivicProof's deterministic "
    "pipeline. Each factual claim is supported by at least one citation to a "
    "stored, immutable artifact with a verified content hash. Risk signals are "
    "generated by rule-based anomaly detectors (no LLM involvement). The auditor "
    "gate verified all claims before approval."
)


def render_case_pack_pdf(
    case_id: str,
    title: str,
    claims: list[dict[str, Any]],
    citations: list[dict[str, Any]],
    audit_events: list[dict[str, Any]],
    pack_hash: str | None = None,
    generated_at: datetime | None = None,
) -> bytes:
    """Render a case pack as a PDF document.

    Returns PDF bytes. All content has already passed the auditor gate.

    Args:
        case_id: UUID of the case.
        title: Case title.
        claims: List of claim dicts with statement, claim_type, confidence.
        citations: List of citation dicts with artifact_id, excerpt.
        audit_events: List of audit event dicts with stage, decision.
        pack_hash: Deterministic hash for replay verification.
        generated_at: Timestamp when pack was generated.
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.platypus import (
            Paragraph,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )
    except ImportError:
        logger.warning(
            "reportlab not installed — returning plaintext fallback. "
            "Install with: pip install reportlab"
        )
        return _render_plaintext_fallback(
            case_id, title, claims, citations, audit_events, pack_hash, generated_at
        )

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "CaseTitle",
        parent=styles["Heading1"],
        fontSize=18,
        spaceAfter=12,
    )
    h2_style = ParagraphStyle(
        "H2",
        parent=styles["Heading2"],
        fontSize=14,
        spaceAfter=8,
        spaceBefore=16,
    )
    body_style = styles["BodyText"]
    disclaimer_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["BodyText"],
        fontSize=8,
        textColor=colors.gray,
        spaceAfter=12,
    )
    meta_style = ParagraphStyle(
        "Meta",
        parent=styles["BodyText"],
        fontSize=9,
        textColor=colors.darkgrey,
    )

    story: list[Any] = []

    # ── Title ──
    story.append(Paragraph(f"CivicProof Case Pack: {_escape(title)}", title_style))
    story.append(Spacer(1, 6))

    # ── Metadata ──
    gen_time = (generated_at or datetime.now(UTC)).strftime("%Y-%m-%d %H:%M UTC")
    story.append(Paragraph(f"<b>Case ID:</b> {case_id}", meta_style))
    story.append(Paragraph(f"<b>Generated:</b> {gen_time}", meta_style))
    if pack_hash:
        story.append(Paragraph(f"<b>Pack Hash:</b> {pack_hash[:24]}...", meta_style))
    story.append(Spacer(1, 12))

    # ── Disclaimer ──
    story.append(Paragraph(_DISCLAIMER, disclaimer_style))
    story.append(Spacer(1, 8))

    # ── Executive Summary ──
    story.append(Paragraph("Executive Summary", h2_style))
    findings = [c for c in claims if c.get("claim_type") == "finding"]
    risk_signals = [c for c in claims if c.get("claim_type") == "risk_signal"]
    hypotheses = [c for c in claims if c.get("claim_type") == "hypothesis"]
    story.append(Paragraph(
        f"This case pack contains <b>{len(claims)}</b> claims: "
        f"{len(findings)} findings, {len(risk_signals)} risk signals, "
        f"and {len(hypotheses)} hypotheses, supported by "
        f"<b>{len(citations)}</b> citations to stored artifacts.",
        body_style,
    ))
    story.append(Spacer(1, 8))

    # ── Claims with Citations ──
    story.append(Paragraph("Claims", h2_style))
    citation_map: dict[str, list[dict]] = {}
    for cit in citations:
        cid = cit.get("claim_id", "")
        citation_map.setdefault(cid, []).append(cit)

    for i, claim in enumerate(claims, 1):
        claim_id = claim.get("claim_id", "")
        ctype = claim.get("claim_type", "unknown")
        confidence = claim.get("confidence", 0.0)
        statement = _escape(claim.get("statement", ""))

        type_label = f"[{ctype.upper()}]"
        story.append(Paragraph(
            f"<b>{i}. {type_label}</b> (confidence: {confidence:.0%}) — {statement}",
            body_style,
        ))

        claim_cits = citation_map.get(claim_id, [])
        for cit in claim_cits:
            artifact_id = cit.get("artifact_id", "unknown")
            excerpt = _escape(cit.get("excerpt", ""))[:200]
            story.append(Paragraph(
                f"&nbsp;&nbsp;&nbsp;↳ <i>Artifact {artifact_id[:12]}...</i>: {excerpt}",
                body_style,
            ))
        story.append(Spacer(1, 4))

    # ── Audit Trail ──
    if audit_events:
        story.append(Paragraph("Audit Trail", h2_style))
        table_data = [["Stage", "Decision", "Timestamp"]]
        for event in audit_events[-10:]:  # Last 10 events
            table_data.append([
                event.get("stage", ""),
                event.get("policy_decision", ""),
                event.get("timestamp", "")[:19],
            ])
        t = Table(table_data, colWidths=[1.5 * inch, 1.5 * inch, 2.5 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ]))
        story.append(t)
        story.append(Spacer(1, 8))

    # ── Methodology Notes ──
    story.append(Paragraph("Methodology", h2_style))
    story.append(Paragraph(_METHODOLOGY_NOTE, body_style))
    story.append(Spacer(1, 12))

    # ── Final Disclaimer ──
    story.append(Paragraph(_DISCLAIMER, disclaimer_style))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()

    logger.info(
        "pdf_rendered case_id=%s claims=%d citations=%d bytes=%d",
        case_id,
        len(claims),
        len(citations),
        len(pdf_bytes),
    )

    return pdf_bytes


def _render_plaintext_fallback(
    case_id: str,
    title: str,
    claims: list[dict[str, Any]],
    citations: list[dict[str, Any]],
    audit_events: list[dict[str, Any]],
    pack_hash: str | None,
    generated_at: datetime | None,
) -> bytes:
    """Plaintext fallback when reportlab is not installed."""
    lines = [
        f"CivicProof Case Pack: {title}",
        f"Case ID: {case_id}",
        f"Generated: {(generated_at or datetime.now(UTC)).isoformat()}",
        f"Pack Hash: {pack_hash or 'N/A'}",
        "",
        "=" * 60,
        _DISCLAIMER,
        "=" * 60,
        "",
        f"CLAIMS ({len(claims)} total):",
        "",
    ]
    for i, claim in enumerate(claims, 1):
        ctype = claim.get("claim_type", "unknown").upper()
        confidence = claim.get("confidence", 0.0)
        statement = claim.get("statement", "")
        lines.append(f"  {i}. [{ctype}] ({confidence:.0%}) {statement}")

    lines.extend(["", f"CITATIONS ({len(citations)} total):", ""])
    for cit in citations:
        lines.append(
            f"  - Claim {cit.get('claim_id', '?')}: "
            f"Artifact {cit.get('artifact_id', '?')}"
        )

    lines.extend(["", _METHODOLOGY_NOTE, "", _DISCLAIMER])
    return "\n".join(lines).encode("utf-8")


def _escape(text: str) -> str:
    """Escape HTML entities for ReportLab paragraphs."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
